## Convolution

In [2]:
import tensorflow as tf
import tensorflow.keras as keras
import numpy as np

conv2D = keras.layers.Conv2D(1, (2, 2), activation='relu')

data_X = np.array([[1, 1, 2],
                   [1, 2, 1],
                   [2, 1, 1]])
data_X = data_X.reshape(1, 3, 3, 1)
data_X = tf.Variable(data_X, dtype=tf.float32)

data_y = np.ones((1, 2, 2, 1))
data_y = tf.Variable(data_y, dtype=tf.float32)

print('\n\n data_X: \n', data_X[0,:,:,0])
print('\n\n data_y: \n', data_y[0,:,:,0])

with tf.GradientTape(persistent=True) as tape: 
    data_after_conv = conv2D(data_X)
    print('\n\n data_after_conv: \n', data_after_conv[0,:,:,0])
    
    # Check the values of the current conv weight
    print('\n\n conv_weight: \n', conv2D.trainable_weights[0][:,:,0,0])
    print('\n conv_bias: \n', conv2D.trainable_weights[1][0])
        
    loss = tf.reduce_mean((data_after_conv-data_y)**2)
    print('\n\n loss: \n', loss)
    
dloss = tape.gradient(loss, data_after_conv)
print('\n\n dloss: \n', dloss[0,:,:,0])

dconv_weight = tape.gradient(loss, conv2D.trainable_weights)
print('\n\n dconv_weight: \n', dconv_weight[0][:,:,0,0])
print('\n dconv_bias: \n', dconv_weight[1][0])



 data_X: 
 tf.Tensor(
[[1. 1. 2.]
 [1. 2. 1.]
 [2. 1. 1.]], shape=(3, 3), dtype=float32)


 data_y: 
 tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


 data_after_conv: 
 tf.Tensor(
[[1.1864988  0.7961735 ]
 [0.7961735  0.23312974]], shape=(2, 2), dtype=float32)


 conv_weight: 
 tf.Tensor(
[[-0.32082075  0.7238367 ]
 [-0.48161376  0.6325483 ]], shape=(2, 2), dtype=float32)

 conv_bias: 
 tf.Tensor(0.0, shape=(), dtype=float32)


 loss: 
 tf.Tensor(0.17649058, shape=(), dtype=float32)


 dloss: 
 tf.Tensor(
[[ 0.09324938 -0.10191324]
 [-0.10191324 -0.38343513]], shape=(2, 2), dtype=float32)


 dconv_weight: 
 tf.Tensor(
[[-0.87744737 -0.6978387 ]
 [-0.6978387  -0.40076286]], shape=(2, 2), dtype=float32)

 dconv_bias: 
 tf.Tensor(-0.49401224, shape=(), dtype=float32)
